[package]
name = "golive"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "golive_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
r2d2_sqlite = { version = "0.35.0", features = ["bundled"] }
rusqlite = { version = "0.40.2", features = ["bundled"] }
r2d2 = "0.8.10"
thiserror = "2.0.20"
uuid = { version = "1.24.1", features = ["v4"] }
xcap = { version = "0.9.8", features = ["image"] }

[dev-dependencies]
tempfile = "3.27.0"

