-- Introduces the Project domain: the top-level container future
-- Processes/Captures/Screenshots/Recordings/Documentation will belong to
-- (via a project_id foreign key, added when those tables are). Nothing
-- else is created here — no Process/Capture/Recording tables yet.

CREATE TABLE IF NOT EXISTS projects (
    id          TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    -- Unix epoch milliseconds (UTC), generated by the backend. created_at
    -- is set once and never changed; updated_at is bumped whenever the
    -- project is modified. See docs/architecture.md for why this
    -- representation (not a formatted string) was chosen.
    created_at  INTEGER NOT NULL,
    updated_at  INTEGER NOT NULL
);

-- The default project listing order is `updated_at DESC` (most recently
-- touched first), so an index on it is worth its (small) upkeep cost.
CREATE INDEX IF NOT EXISTS idx_projects_updated_at ON projects (updated_at DESC);
