-- Introduces the Process domain: a Process belongs to exactly one
-- Project. Deleting a Project cascades to delete its Processes at the
-- database level (ON DELETE CASCADE) -- the application never loops to
-- manually delete related rows; this relationship owns that behavior.
--
-- Process is the future parent/context for Captures, screen/microphone
-- recordings, transcripts, and AI-generated analysis -- none of those
-- tables exist yet.

CREATE TABLE IF NOT EXISTS processes (
    id          TEXT PRIMARY KEY,
    project_id  TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    -- Stable string representation of the ProcessStatus enum (draft /
    -- in_progress / completed) -- never a raw integer. See
    -- docs/architecture.md ("Process status") for why.
    status      TEXT NOT NULL DEFAULT 'draft',
    -- Unix epoch milliseconds (UTC), generated by the backend. Same
    -- convention as projects.created_at/updated_at.
    created_at  INTEGER NOT NULL,
    updated_at  INTEGER NOT NULL
);

-- Every process lookup goes through its project, so this index is
-- essentially required.
CREATE INDEX IF NOT EXISTS idx_processes_project_id ON processes (project_id);

-- Supports the actual (and only) listing query: "processes for project X,
-- most recently updated first."
CREATE INDEX IF NOT EXISTS idx_processes_project_id_updated_at
    ON processes (project_id, updated_at DESC);
