-- Introduces the Capture domain: a Capture belongs to exactly one
-- Process. Deleting a Process cascades to delete its Captures at the
-- database level (ON DELETE CASCADE) -- the application never loops to
-- manually delete related rows; this relationship owns that behavior,
-- same as processes.project_id -> projects (0003_processes.sql). Because
-- processes.project_id already cascades from projects, deleting a Project
-- transitively cascades: Project -> Process -> Capture.
--
-- A Capture is metadata only -- no screenshot/recording/media file is
-- attached yet. See docs/architecture.md ("Capture domain") for why.

CREATE TABLE IF NOT EXISTS captures (
    id          TEXT PRIMARY KEY,
    process_id  TEXT NOT NULL REFERENCES processes(id) ON DELETE CASCADE,
    -- Stable string representation of the CaptureType enum (screenshot /
    -- recording / note) -- never a raw integer. See
    -- docs/architecture.md ("Capture domain") for why.
    type        TEXT NOT NULL,
    title       TEXT NOT NULL,
    description TEXT,
    -- Unix epoch milliseconds (UTC), generated by the backend. Same
    -- convention as projects/processes created_at/updated_at.
    created_at  INTEGER NOT NULL,
    updated_at  INTEGER NOT NULL
);

-- Every capture lookup goes through its process, so this index is
-- essentially required.
CREATE INDEX IF NOT EXISTS idx_captures_process_id ON captures (process_id);

-- Supports the actual (and only) listing query: "captures for process X,
-- most recently updated first."
CREATE INDEX IF NOT EXISTS idx_captures_process_id_updated_at
    ON captures (process_id, updated_at DESC);
