-- Introduces the ProcessVersion domain (TASK-018): one row per
-- AI-generated structured draft (TASK-017's `generate_process_draft`).
-- A ProcessVersion belongs to exactly one Process; deleting a Process
-- cascades to delete its versions at the database level (ON DELETE
-- CASCADE), same relationship shape as processes.project_id ->
-- projects and captures.process_id -> processes before it.
--
-- Deliberately append-only and immutable: regenerating never overwrites
-- or updates an existing row -- it INSERTs a new one -- which is the
-- actual product rule this table exists to enforce (see
-- docs/architecture.md SS5, "AI-generated process regeneration must not
-- silently overwrite a previous process version"). No `updated_at`
-- column, unlike projects/processes/captures: those are user-editable
-- domain records; a ProcessVersion is a point-in-time generation
-- result that is never edited in place at this stage (TASK-019 decides
-- what editing means for this table, if anything).

CREATE TABLE IF NOT EXISTS process_versions (
    id          TEXT PRIMARY KEY,
    process_id  TEXT NOT NULL REFERENCES processes(id) ON DELETE CASCADE,
    -- The full ai::ProcessDraft (summary + ordered steps, each with a
    -- title/description/capture_ids), serialized as JSON. Not
    -- normalized into separate step/capture-reference tables: nothing
    -- in this task needs to query or edit the content at the field
    -- level (see docs/architecture.md, "Process draft persistence") --
    -- that's TASK-019's job, and it can choose to normalize this then
    -- if it needs to.
    content     TEXT NOT NULL,
    -- Unix epoch milliseconds (UTC), generated by the backend. Same
    -- convention as every other table's created_at.
    created_at  INTEGER NOT NULL
);

-- Supports the actual (and only) listing query: "every version of
-- process X, newest first" -- the same "list belongs-to a parent,
-- ordered by time" shape captures.process_id/updated_at already uses.
CREATE INDEX IF NOT EXISTS idx_process_versions_process_id_created_at
    ON process_versions (process_id, created_at DESC);
